### ISSUE TITLE
Indexes not created when multiple cashboxes share the same DB instance

### ISSUE THREAD

**Issue by darek-phorest** [fiskaltrust/middleware#121]
Hi there, 

It seams that the code that checks the existence of the index doesn't do it per `table_schema` which means that it will only add it once for the first cashbox that runs on byodc. Other cashboxes will end up with the `no` indexes created. 

https://github.com/fiskaltrust/middleware/blob/85bf5ebef55a32e79a55d207f00ad80767103a5c/queue/src/fiskaltrust.Middleware.Storage.MySQL/Migrations/005_Indices.mysql#L16

**Comment by volllly** [comment]
Hey @darek-phorest, thanks for submitting this issue. We've just released MySQL Queue `v1.3.45` and byodc `1.3.45-rc2-bullseye`/`1.3.45-rc2-jammy` containing a fix 🚀
