### ISSUE TITLE
Restoring nuget packages without access to private feed not working

### ISSUE THREAD

**Issue by StefanKert** [fiskaltrust/middleware#156]
Currently it is not possible to build / debug the Middleware without having access to the private nuget feed that is being used in the pipeline.  Most of the packages are already publicly available but some of them (e.g. fiskaltrust.storage) are only internal. We should find a way to make these packages available so that contributors can build the middleware

**Comment by volllly** [comment]
Hey, all of these packages should be available.

Can you give us the exact packages and versions so we can fix that?

**Comment by StefanKert** [comment]
So I've tried to git clone in a docker container to simulate a device that is not setup with our nuget feeds. When starting GitHub codespaces you can reproduce this issue by opening the terminal and restoring the different solutions. 

Added the public nuget feed to nuget.config so right now we are able to restore most packages but it looks like we are having a few references to old packages that are not pushed to the public feed:

- fiskaltrust.Middleware.Abstractions 1.3.1
- fiskaltrust.storage.serialization 1.3.1

We should decide if we update these packages or if we roll out the old versions :)

**Comment by volllly** [comment]
We've released these packages to our public azure devops feed and added the feed to the `nuget.config`.

AFAICT the issue is resolved (the solutions are building in codespaces). Can you verify that?

**Comment by StefanKert** [comment]
Yep :) worked Thanks!
