### ISSUE TITLE
Fiskaly number of transactions maxes at 100

### ISSUE THREAD

**Issue by StefanKert** [fiskaltrust/middleware#170]
The current implementation of the FiskalyCertified SCU doesn't report the actual count of open transactions if there are more than 100. This is due to the fact that the Fiskaly API uses pagination and we are basing the count on the retruned active transactions.

Since the case of > 100 open transactions is not really likely we shouldn't have to download all transactions to the scu because that could delay the startup.

What we should fix though is the count that is being reported. The TSS endpoint offers the actual count of open transactions (https://developer.fiskaly.com/api/kassensichv/v2#operation/retrieveTss) so we can use that instead of the current implementation

**Comment by TSchmiedlechner** [comment]
We should definitely do that 💯 

Thought a bit why this was initially implemented that way, and I think it origins from the v1 implementation (where the `tss` endpoint didn't have the `number_active_transactions` property). I don't think there's a valid reason anymore for doing this the way we've implemented it right now.
