### ISSUE TITLE
IT Middleware doesn't allow cbUser field to be a string 

### ISSUE THREAD

**Issue by StefanKert** [fiskaltrust/middleware#171]
While we allow user defined string values for the `cbUser` field in other markets we are restricting this to being a number from 1-12. This is a somehow breaking change for most existing POSCreators since the do very often include the real users name.

For fixing this we will have to do two things

- Remove the restriction from the current implementation and allow user defined values 
- Figure out a internal mapping to the Operator that is being used on the RT Printer / RT Server

**Comment by forsthug** [comment]
As discussed we will use 1 by default as the value is known to the pos system and the middleware
