### ISSUE TITLE
Error handling improvement suggestion from customer-email

### ISSUE THREAD

**Issue by steininger** [fiskaltrust/middleware#219]
Dear fiskaltrust team,

we kindly ask, if it is possible to extend your IPos.v0 interface.
Currently, erroneous requests are rejected where we would expect a fiskaltrust.ifPOS.v0.ReceiptResponse with some error details.
This is very difficult to handle.

If, for instance, we would send a fiskaltrust.ifPOS.v0.ReceiptRequest with an invalid value in ftCashBoxID, we suggest to return an answer like the JSON sample below:

-	ftState should indicate a reject, e.g. "0x44450000000000FF"
-	ftStateData could return the reason for the rejection, e.g. "ftCashBoxID  invalid"
Another place to return the reason could be a ftSignatureItem with a special ftSignatureType (e.g. "0x44450000000000FF")
-	Since the data is not stored on your side, your return values, e.g, ftQueueItemID and ftQueueRow , should be empty or -1.
-	To make it more obvious, that this is a rejection, no data from the cbReceiptRequest needs to be returned, e.g. ftCashBoxID.

In JSON the fiskaltrust.ifPOS.v0.ReceiptResponse Would then be like this:
{
  "ftCashBoxID": "",
  "ftQueueID": "",
  "ftQueueItemID": "",
  "ftQueueRow": -1,
  "cbTerminalID": "",
  "cbReceiptReference": "",
  "ftCashBoxIdentification": "",
  "ftReceiptIdentification": "",
  "ftReceiptMoment": "2021-04-30T04:35:57.126946Z",
  "ftSignatures": [
    {
      "ftSignatureFormat": "0x1",
      "ftSignatureType": "0x44450000000000FF",
      "Caption": "Error",
      "Data": " ftCashBoxID  invalid "
    }
  ],
  "ftState": "0x44450000000000FF",
  "ftStateData": "{\"Error\":\" ftCashBoxID  invalid\"}"
}

**Comment by TSchmiedlechner** [comment]
Sounds like a great idea for sure 😁

**Comment by StefanKert** [comment]
Not really closed, we should consider this for AT/DE/FR too

**Comment by StefanKert** [comment]
Completed with the latest releases
