### ISSUE TITLE
Receipt queue database not refreshed

### ISSUE THREAD

**Issue by CezBok** [fiskaltrust/middleware#224]
We got issues with queue for both active locations: FR0147 and FR4667. 
FR4667 latest data are from 07/09/2023
FR0147 latest data are from 28/09/2023 but the reason for shorter delay is that I requested manual push for the data.
![FR4667](https://github.com/fiskaltrust/middleware/assets/150252439/bafec737-b4af-4fcb-92c1-749620ab272e)
![FR0147](https://github.com/fiskaltrust/middleware/assets/150252439/8264389f-89a8-4ba9-adf1-82bc73cbadd7)

**Comment by volllly** [comment]
Hey, thanks for reporting this.

Cloud Cashboxes can currently experience delays until the data shows up in the portal.

We're aware of the issue and are working on a solution to the problem.

**Comment by CezBok** [comment]
Hi,

Cloud Cashboxes not only currently experience delays but also for past 6 months.
Not sure if you changed something, but receipt journal from FR0147 is now updated in FT portal, which is strange because for FR4667 last is from 7th of September.

Pozdrawiam / Best Regards

Cezary Bokun



General Information

**Comment by CezBok** [comment]
Hi,

Can you kindly response about configuration difference between FR0147 and FR4667? Why from FR0147 data is updated when is missing from FR4667...

Pozdrawiam / Best Regards

Cezary Bokun



General Information

From: Bokun Cezary (H&M PL: PL: Business Tech) ***@***.***>
Sent: czwartek, 9 listopada 2023 13:03
To: fiskaltrust/middleware ***@***.***>; fiskaltrust/middleware ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [fiskaltrust/middleware] Receipt queue database not refreshed (Issue #224)

Hi,

Cloud Cashboxes not only currently experience delays but also for past 6 months.
Not sure if you changed something, but receipt journal from FR0147 is now updated in FT portal, which is strange because for FR4667 last is from 7th of September.

Pozdrawiam / Best Regards

Cezary Bokun

**Comment by Bluette-C-Riviere** [comment]
Hi @CezBok ,
I wanted to inform you that the fix for the data upload issue on the portal was implemented last week. We are actively monitoring the system to ensure that everything is functioning smoothly. If you encounter any issues or have any concerns, please feel free to reach out.

**Comment by CezBok** [comment]
Thank you. Based on my observation issue should be solved.
