### ISSUE TITLE
DE - FCC SetFccHeapMemory has no effect on run script

### ISSUE THREAD

**Issue by saschaknapp** [fiskaltrust/middleware#247]
### Description
In package version fiskaltrust.Middleware.SCU.DE.DeutscheFiskal v1.3.40 we introduced the possibility to set the heap size for the FCC to tackle issues with OutOfMemory exceptions with large TAR files. The parameter "SetFccHeapMemory" can be set in the portal and is supposed to let the fcc run with this value in the cases of...

- FCC initialization
- FCC update
- FCC regular service run

### The Problem
It seems that the heap setting is not having an effect on the regular service running. We use the run_fcc.bat/sh to start the FCC. Therefore the heap in the run_fcc.bat (-Xmx) should change to the value set in SetFccHeapMemory. This doesn't happen. The fcc always starts with -xmx 256 even if the value is set. I tried to find the reason but i don't see any issue with the function we use to change the .bat:
https://github.com/fiskaltrust/middleware/blob/b3849f7623beb41b54114355d21c85206df62259/scu-de/src/fiskaltrust.Middleware.SCU.DE.DeutscheFiskal/Helpers/ConfigHelper.cs#L11

### To Reproduce

- Set the "SetFccHeapMemory" in the SCU with a value different than 256 (e.g. 1024)
- RebuildConfiguration
- Restart the middleware service
- Check the middleware log for the FCC startup and see if the -xmx value has the value you configured in the SCU

## Tasks
- [ ] The FCC should start with the correct heap memory
- [ ] The logs should indicate the correct value

**Comment by forsthug** [comment]
Value is set and written to run_fcc.bat.  Possible values 256, 512, 1024
Config Parameter 

![image](https://github.com/fiskaltrust/middleware/assets/85173816/7a58dd47-ebea-4fb3-9d5e-b1516d6c7061)


![image](https://github.com/fiskaltrust/middleware/assets/85173816/0aae8577-f76b-4cff-ac22-5e9a55a59fde)

![image](https://github.com/fiskaltrust/middleware/assets/85173816/763dbdf6-b2d3-4b0a-bbd7-64d73076024c)

**Comment by saschaknapp** [comment]
So the parameter is without "Set"? Then our releasenotes were wrong https://docs.fiskaltrust.cloud/changelog/middleware/1.3.40#feature-heap-memory-is-now-configurable-for-deutschefiskal-and-swissbitcloud-scus

**Comment by forsthug** [comment]
We`ll fix the docu today.
