### ISSUE TITLE
DFKA with Voucher payment type don´t sum up correct

### ISSUE THREAD

**Issue by forsthug** [fiskaltrust/middleware#302]
### Describe the bug
When adding a Voucher via Payitem, the paid sum is is not including the Voucher.

### To Reproduce
Send receipt with 
```json
  "cbPayItems": [
    {
      "Quantity": 1,
      "Description": "Gutschein Werbering",
      "Amount": 50,
      "ftPayItemCase": "4919338167972134925",
      "ftPayItemCaseData": "",
      "AccountNumber": "",
      "CostCenter": "",
      "MoneyGroup": "",
      "MoneyNumber": "",
      "Moment": "2024-05-16T08:06:18Z"
    },
    {
      "Quantity": 1,
      "Description": "Bargeld",
      "Amount": 5,
      "ftPayItemCase": "4919338167972134913",
      "ftPayItemCaseData": "",
      "AccountNumber": "",
      "CostCenter": "",
      "MoneyGroup": "",
      "MoneyNumber": "",
      "Moment": "2024-05-16T08:06:29Z"
    },
```
dfka:
```json
        "head": {
          "type": "Beleg",
          "closing_cash_register": {
            "id": ""
          },
          "storno": false,
          "id": "",
          "number": 88,
          "timestamp_start": "2024-05-16T07:30:36Z",
          "timestamp_end": "2024-05-16T07:33:59Z",
          "user": {
            "id": "Support",
            "name": "Support"
          },
          "allocation_groups": [
            "dfae9f37-1bf3-4ad6-9c88-bdb9f45faf31"
          ],
          "custom_fields": {
            "QueueItemId": "..."
          }
        },
        "data": {
          "full_amount_incl_vat": 5.00,
          "amounts_per_vat_id": [
            {
              "id": 1,
              "incl_vat": 55.00,
              "excl_vat": 46.22,
              "vat": 8.78
            },
            {
              "id": 6,
              "incl_vat": 0.00,
              "excl_vat": 0.00,
              "vat": 0.00
            },
            {
              "id": 5,
              "incl_vat": -50.00,
              "excl_vat": -50.00,
              "vat": 0.00
            }
          ],
          "type": "",
          "payment_types": [
            {
              "type": "Bar",
              "currency_code": "EUR",
              "amount": 5.00
            },
            {
              "type": "Bar",
              "currency_code": "EUR",
              "amount": 0.00
            }
          ],
```

[voucherDfka.json](https://github.com/user-attachments/files/15530861/voucherDfka.json)
[testVoucher.json](https://github.com/user-attachments/files/15530867/testVoucher.json)

### Further technical details & context
Check reference the dsfinvk-definition on multiuse vouchers

# Tasks
- [x] Fix the incorrect summing for all ways of doing vouchers (chargeitem voucher, payitem voucher / buying + redeeming)
- [x] Test by either reproducing the issue or using the Queue from the inquiry, and importing the data in AmadeusVerify

**Comment by TSchmiedlechner** [comment]
Link to the inquiry in Slack:
https://fiskaltrust.slack.com/archives/C06DK7GAV8D/p1717049654686629

**Comment by forsthug** [comment]
We checkt this case on Amadeus Verify and against the Dsfinvk-Documentation and find alle values and sums are correct.

![Image](https://github.com/fiskaltrust/middleware/assets/85173816/e728f57f-ea9f-42a9-9bd0-398115b6c2ed)

**Comment by forsthug** [comment]
Fehler 515


![Image](https://github.com/fiskaltrust/middleware/assets/85173816/21acebf4-9389-483c-bb77-b0442f4ba97f)



Dsfinvk Definition

In den Bestellungen findet sich keine Definition wo das Vorzeichen gesetzt wird.  Generell gilt:
 

![Image](https://github.com/fiskaltrust/middleware/assets/85173816/2eaab270-015a-4956-af6e-2ba3e64d61df)


Fix MW
 
https://github.com/fiskaltrust/middleware/pull/320/files
