### ISSUE TITLE
Fiskal Trust portal unavailable

### ISSUE THREAD

**Issue by CezBok** [fiskaltrust/middleware#334]
Since yesterday I got often error on my account: cezary.bokun@hm.com
When opening any feauture in Fiskal Trust portal for France it shows me attached error: _You don't have access/read access rights needed to access this area! Please contact your primary contact._

From time to time I can access without issues: eg. This morning until now was fine. 
![screenshot](https://github.com/user-attachments/assets/91d3781b-bbe8-4353-98e5-c8640bc9f5d0)

**Comment by CezBok** [comment]
It seems that issue is specific to my account. Everything works as expected for oskar.borg@bontouch.com.

**Comment by CezBok** [comment]
recent observations indicate that sometimes access works (now for example) and sometimes it doesn't (yesterday afternoon).

**Comment by TSchmiedlechner** [comment]
Hi @CezBok, thanks for reaching out! We unfortunately cannot provide end user support for the Portal via this repository, but we're looking into the issue and someone from our support team will reach out to you shortly.
