### ISSUE TITLE
Unify common middleware processes

### ISSUE THREAD

**Issue by StefanKert** [fiskaltrust/middleware#99]
Currently the queue is only used for basic operations (e.g. creating queue items & chaining) and all other steps are forwarded to the market specific processor. This can lead to make implementations of common processes (e.g. daily closing) drift apart. 

Also we need to re-implement all these common processes for each new market.

By unifying these processes and creating a shared implementation in the basic queue we will be able to enforce the same processes in all markets and also allow users from markets that are not implemented yet to still use all common processes for a new market by just sending the market code at the beginning of the receipt case (switching from DE 4445 to IT 4954).

The processes that should be shared are mainly those described in the general part of the interface documentation. https://docs.fiskaltrust.cloud/docs/poscreators/middleware-doc

## Common receipts

While there might be specific actions required for each of these processes (e.g. DE requires TAR files to being exported on a daily closing), we should be able to find a common way to implement the following processes:

- Zero Receipt
- Start Receipt 
- Stop Receipt 
- End of Failure Receipt
- Daily Closing
- Monthly Closing
- Yearly Closing
- Handwritten receipt (?)
- "Nacherfassung" (?)

## Default receipt - Chaining / Security Mechanism

In addition to that we could think about implementing a common receipt that can be used with a common sign processor without calling country specific logic. This could be especially helpful for markets that don't really depend on specific external components (like a TSE) and can already benefit from the SecurityMechanism.

## Common error handling

While we have some specific things to check for each market there are some prerequisites that we expect when operating the middleware. The following is a list of these processes and can be potentially extended:

- Allowing receipts different than start receipt only when queue is started 
- Checking the sum amounts of pay items & charge items
- ?

**Comment by volllly** [comment]
FYI We've decided to leave the current markets as is (for now) but go for it in the new markets and have already implemented a [general/default receipts](https://github.com/fiskaltrust/middleware/tree/56117-Implement-basic-receipts-in-the-Italian-Middleware/queue/src/fiskaltrust.Middleware.Contracts/RequestCommands) architecture in the italian queue.
